#!/usr/bin/env python3
"""Generate code from the design sheets (the source of truth). Run preflight first.
Outputs:
  game/Generated/Sheets.g.cs   - one record type per sheet, one static instance per row
  extract/plan.json            - what the extractors pull from each game (derived from sheets)"""
import json, pathlib, re, subprocess, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from preflight import load, check

def pascal(s): return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]", s) if p)
def cstype(t):
    return {"string": "string", "int": "int", "number": "double", "bool": "bool"}.get(t, "string[]" if t.startswith("refs:") else "string")
def lit(v, t):
    if t.startswith("refs:"): return "new string[] {" + ", ".join(json.dumps(x) for x in v) + "}"
    if t == "bool": return "true" if v else "false"
    if t == "number": return repr(float(v))
    if t == "int": return str(v)
    return json.dumps(v, ensure_ascii=False)

sheets = load()
errors, _ = check(sheets)
if errors:
    sys.exit("preflight has blocking problems; run tools/preflight.py")

out = ["// <auto-generated> by tools/gen.py from design/sheets - edit the sheets, not this file.", "#nullable enable",
       "namespace OnlyBebop.Sheets;", ""]
for name, s in sheets.items():
    T = pascal(name) + "Row"
    cols = s["columns"]
    out.append(f"/// <summary>{s.get('about','')}</summary>")
    out.append(f"public sealed record {T}(" + ", ".join(f"{cstype(t)} {pascal(c)}" for c, t in cols.items()) + ", string[] Unverified);")
    out.append(f"public static class {pascal(name)}")
    out.append("{")
    for r in s["rows"]:
        args = ", ".join(lit(r[c], t) for c, t in cols.items())
        unv = "new string[] {" + ", ".join(json.dumps(x) for x in r.get("_unverified", [])) + "}"
        out.append(f"    public static readonly {T} {pascal(r['id'])} = new({args}, {unv});")
    out.append(f"    public static readonly {T}[] All = {{ " + ", ".join(pascal(r["id"]) for r in s["rows"]) + " };")
    out.append("}")
    out.append("")
(ROOT / "game" / "Generated").mkdir(parents=True, exist_ok=True)
(ROOT / "game" / "Generated" / "Sheets.g.cs").write_text("\n".join(out))

rows = lambda n: {r["id"]: r for r in sheets[n]["rows"]}
au, he, ab, mv = rows("audio"), rows("heroes"), rows("abilities"), rows("movement")
plan = {
    "deadlock": {
        "archive": rows("games")["deadlock"]["archive"],
        "units_per_meter": rows("games")["deadlock"]["units_per_meter"],
        "heroes": [{"id": h["id"], "vdata_key": h["vdata_key"], "model": h["model"], "playable": h["playable"]} for h in he.values() if h["playable"]],
        "roster": True,
        "abilities": [{"id": a["id"], "vdata_key": a["vdata_key"], "icon": a["icon_image"]} for a in ab.values()],
        "stats": {**{m["id"]: m["vdata_path"] for m in mv.values() if m["vdata_path"].startswith(("heroes.vdata/", "abilities.vdata/"))},
                  **{f'{a["id"]}.{k}': f'abilities.vdata/{a["vdata_key"]}/{a[k + "_prop"]}' for a in ab.values() for k in ("range", "cooldown", "launch") if a[k + "_prop"] != "-"}},
        "sounds": [{"id": a["id"], "event": a["event_or_asset"], "script": a["script"]} for a in au.values() if a["game"] == "deadlock" and a["id"] != "none"],
    },
    "onlyup": {
        "appid": rows("games")["onlyup"]["steam_appid"],
        "units_per_meter": rows("games")["onlyup"]["units_per_meter"],
        "music": au["onlyup_music"]["event_or_asset"],
    },
}
(ROOT / "extract").mkdir(exist_ok=True)
(ROOT / "extract" / "plan.json").write_text(json.dumps(plan, indent=2))
print("generated game/Generated/Sheets.g.cs and extract/plan.json")
